name: Build and Deploy to main
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  PROJECT: 'cpg-common'
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  DOCKER_PREFIX: 'australia-southeast1-docker.pkg.dev'
  IMAGES_PREFIX: 'australia-southeast1-docker.pkg.dev/cpg-common/images'

jobs:
  get_next_version:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_next_version.outputs.next_version }}
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref == 'refs/heads/main' && 'main' || github.event.ref }}
          fetch-depth: 0
          persist-credentials: false
          submodules: 'recursive'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - id: 'google-cloud-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.FETCH_TAGS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.FETCH_TAGS_WORKLOAD_SERVICE_ACCOUNT }}

      - id: 'google-cloud-sdk-setup'
        name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT }}

      - name: 'Get current version'
        id: get_next_version
        run: |
          next_version=$(python .github/workflows/get_version.py)
          echo "next_version=$next_version" >> "$GITHUB_OUTPUT"

  build_deploy_main:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - get_next_version
    if: ${{ needs.get_next_version.outputs.matrix != '{"include":[]}' && needs.get_next_version.outputs.matrix != '' }}
    strategy:
      matrix: ${{ fromJson(needs.get_next_version.outputs.matrix) }}
    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: 'google-cloud-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.PROD_IMG_DEPLOYER_POOL }}
          service_account: ${{ secrets.PROD_IMG_DEPLOYER_SA }}

      - id: 'google-cloud-sdk-setup'
        name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - run: |
          gcloud auth configure-docker ${{ env.DOCKER_PREFIX }}

      - name: 'build image'
        run: |
          docker build . -f Dockerfile \
          --build-arg VERSION=${{ matrix.tag }} \
          --tag ${{ env.IMAGES_PREFIX }}/${{ matrix.name }}:${{ matrix.tag }}

      - name: 'push image'
        run: |
          docker push "${{ env.IMAGES_PREFIX }}/${{ matrix.name }}:${{ matrix.tag }}"
