name: Docker

## add something in here to choose when this workflow runs
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use (defaults to "test")'
        default: "test"
#  push:
#    branches:
#      - main

permissions:
  id-token: write
  contents: read

env:
  VERSION: 0.1.0

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash -l {0}
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      # TODO(you) choose the name for your image
      IMAGE_NAME: workflow_name
      DOCKER_DEV: australia-southeast1-docker.pkg.dev/cpg-common/images-dev
      DOCKER_MAIN: australia-southeast1-docker.pkg.dev/cpg-common/images
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - id: "google-cloud-auth"
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1051897107465/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gh-images-deployer@cpg-common.iam.gserviceaccount.com"

      - name: set up gcloud sdk
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cpg-common

      - name: gcloud docker auth
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: build
        run: |
          docker build . -f Dockerfile --tag $IMAGE_NAME:${{ github.sha }}

      # TODO(you) choose how/when to push the resulting image
      - name: Push from merge to main
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $DOCKER_MAIN/$IMAGE_NAME:$VERSION
          docker push $DOCKER_MAIN/$IMAGE_NAME:$VERSION

      - name: Push manually triggered build
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name != 'main' }}
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $DOCKER_DEV/$IMAGE_NAME:${{github.event.inputs.tag}}
          docker push $DOCKER_DEV/$IMAGE_NAME:${{github.event.inputs.tag}}

      - name: Push Pull Request triggered build
        if: ${{ github.event_name == 'pull_request' && github.ref_name != 'main' }}
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $DOCKER_DEV/$IMAGE_NAME:PR_${{github.event.number}}
          docker push $DOCKER_DEV/$IMAGE_NAME:PR_${{github.event.number}}
