name: Run Pytest
on:
  # Running on pull-requests and new pushes to main
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: Install packages
      run: pip install .[test]

    - name: Run pre-commit
      run: pytest test
